### PR TITLE
Add notes about usage of rustfmt

### PR DESCRIPTION
**Pull request by 197g**
@Atul9 Here's the note about rustfmt as you've suggested.

### CODE REVIEW

**Comment by Atul9** [comment]
image
I think if we rename `fmt-internal` to `FmtInternal` the hyperlink for the text `You can read more in-depth opinions in the internals thread` & for fmt-image will work. Can you please check?

**Comment by Atul9** [comment]
For the wording, can you please run it once on https://app.grammarly.com/ & correct the suggestion?

**Comment by Atul9** [comment]
LGTM, @HeroicKatora you/someone who has acces to merge can merge this. I don't have access to merge this PR.

**Comment by 197g** [comment]
The problem with links was a surplus `)` at the end of the first link which had the effect of markdown interpreting both as a single paragraph of raw text. Manual normalization of the link label should only be necessary for intra-page link targets themselves. I'm not yet sure about using grammarly regularly, but it did complain about my punctuation and nothing else :smile:.

**Pull request merged**
